---
- hosts: 127.0.0.1
  tasks:
  - rpm_key:
      key: https://packages.microsoft.com/keys/microsoft.asc
      state: present

  - name: Install visual studio code repo
    copy: src=../files/vscode.repo dest=/etc/yum.repos.d/vscode.repo

  - name: Install visual code
    dnf: pkg=code state=present
